# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\code\CppDistro\cmake\bin\cmake.exe

# The command to remove a file.
RM = C:\code\CppDistro\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\code\kolobok

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\code\kolobok

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\code\CppDistro\cmake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\code\CppDistro\cmake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\code\kolobok\CMakeFiles C:\code\kolobok\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\code\kolobok\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kolobok_game

# Build rule for target.
kolobok_game: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 kolobok_game
.PHONY : kolobok_game

# fast build rule for target.
kolobok_game/fast:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/build
.PHONY : kolobok_game/fast

kolobok_game/field.obj: kolobok_game/field.cpp.obj

.PHONY : kolobok_game/field.obj

# target to build an object file
kolobok_game/field.cpp.obj:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/field.cpp.obj
.PHONY : kolobok_game/field.cpp.obj

kolobok_game/field.i: kolobok_game/field.cpp.i

.PHONY : kolobok_game/field.i

# target to preprocess a source file
kolobok_game/field.cpp.i:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/field.cpp.i
.PHONY : kolobok_game/field.cpp.i

kolobok_game/field.s: kolobok_game/field.cpp.s

.PHONY : kolobok_game/field.s

# target to generate assembly for a file
kolobok_game/field.cpp.s:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/field.cpp.s
.PHONY : kolobok_game/field.cpp.s

kolobok_game/ghost.obj: kolobok_game/ghost.cpp.obj

.PHONY : kolobok_game/ghost.obj

# target to build an object file
kolobok_game/ghost.cpp.obj:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/ghost.cpp.obj
.PHONY : kolobok_game/ghost.cpp.obj

kolobok_game/ghost.i: kolobok_game/ghost.cpp.i

.PHONY : kolobok_game/ghost.i

# target to preprocess a source file
kolobok_game/ghost.cpp.i:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/ghost.cpp.i
.PHONY : kolobok_game/ghost.cpp.i

kolobok_game/ghost.s: kolobok_game/ghost.cpp.s

.PHONY : kolobok_game/ghost.s

# target to generate assembly for a file
kolobok_game/ghost.cpp.s:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/ghost.cpp.s
.PHONY : kolobok_game/ghost.cpp.s

kolobok_game/main.obj: kolobok_game/main.cpp.obj

.PHONY : kolobok_game/main.obj

# target to build an object file
kolobok_game/main.cpp.obj:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/main.cpp.obj
.PHONY : kolobok_game/main.cpp.obj

kolobok_game/main.i: kolobok_game/main.cpp.i

.PHONY : kolobok_game/main.i

# target to preprocess a source file
kolobok_game/main.cpp.i:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/main.cpp.i
.PHONY : kolobok_game/main.cpp.i

kolobok_game/main.s: kolobok_game/main.cpp.s

.PHONY : kolobok_game/main.s

# target to generate assembly for a file
kolobok_game/main.cpp.s:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/main.cpp.s
.PHONY : kolobok_game/main.cpp.s

kolobok_game/pacman.obj: kolobok_game/pacman.cpp.obj

.PHONY : kolobok_game/pacman.obj

# target to build an object file
kolobok_game/pacman.cpp.obj:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/pacman.cpp.obj
.PHONY : kolobok_game/pacman.cpp.obj

kolobok_game/pacman.i: kolobok_game/pacman.cpp.i

.PHONY : kolobok_game/pacman.i

# target to preprocess a source file
kolobok_game/pacman.cpp.i:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/pacman.cpp.i
.PHONY : kolobok_game/pacman.cpp.i

kolobok_game/pacman.s: kolobok_game/pacman.cpp.s

.PHONY : kolobok_game/pacman.s

# target to generate assembly for a file
kolobok_game/pacman.cpp.s:
	$(MAKE) -f CMakeFiles\kolobok_game.dir\build.make CMakeFiles/kolobok_game.dir/kolobok_game/pacman.cpp.s
.PHONY : kolobok_game/pacman.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... kolobok_game
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... kolobok_game/field.obj
	@echo ... kolobok_game/field.i
	@echo ... kolobok_game/field.s
	@echo ... kolobok_game/ghost.obj
	@echo ... kolobok_game/ghost.i
	@echo ... kolobok_game/ghost.s
	@echo ... kolobok_game/main.obj
	@echo ... kolobok_game/main.i
	@echo ... kolobok_game/main.s
	@echo ... kolobok_game/pacman.obj
	@echo ... kolobok_game/pacman.i
	@echo ... kolobok_game/pacman.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

